// Copyright 2022 The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by "make plugins".

package plugins

import (
	// Register aws plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/aws"

	// Register azure plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/azure"

	// Register consul plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/consul"

	// Register digitalocean plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/digitalocean"

	// Register dns plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/dns"

	// Register eureka plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/eureka"

	// Register gce plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/gce"

	// Register hetzner plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/hetzner"

	// Register ionos plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/ionos"

	// Register kubernetes plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/kubernetes"

	// Register linode plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/linode"

	// Register marathon plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/marathon"

	// Register moby plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/moby"

	// Register nomad plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/nomad"

	// Register openstack plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/openstack"

	// Register ovhcloud plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/ovhcloud"

	// Register puppetdb plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/puppetdb"

	// Register scaleway plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/scaleway"

	// Register triton plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/triton"

	// Register uyuni plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/uyuni"

	// Register vultr plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/vultr"

	// Register xds plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/xds"

	// Register zookeeper plugin.
	_ "github.com/zzylol/prometheus-sketches/discovery/zookeeper"
)
